-- MySQL Script generated by MySQL Workbench
-- Wed May 31 23:25:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oop` DEFAULT CHARACTER SET utf8 ;
USE `oop` ;

-- -----------------------------------------------------
-- Table `oop`.`CERTIFICATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`CERTIFICATE` (
  `cert_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`cert_id`),
  UNIQUE INDEX `cert_id_UNIQUE` (`cert_id` ASC) INVISIBLE)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `oop`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`USERS` (
  `_id` INT NOT NULL,
  `cert_id` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`_id`),
  UNIQUE INDEX `_id_UNIQUE` (`_id` ASC) VISIBLE,
  INDEX `fk_USERS_CERTIFICATE1_idx` (`cert_id` ASC) VISIBLE,
  UNIQUE INDEX `CERTIFICATE_cert_id_UNIQUE` (`cert_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_CERTIFICATE1`
    FOREIGN KEY (`cert_id`)
    REFERENCES `oop`.`CERTIFICATE` (`cert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop`.`FORUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`FORUM` (
  `cert_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `score` INT NULL,
  `text` VARCHAR(45) NULL,
  `likes` INT NULL,
  `dislikes` INT NULL,
  INDEX `fk_FORUM_CERTIFICATE1_idx` (`cert_id` ASC) VISIBLE,
  UNIQUE INDEX `cert_id_UNIQUE` (`cert_id` ASC) VISIBLE,
  CONSTRAINT `fk_FORUM_CERTIFICATE1`
    FOREIGN KEY (`cert_id`)
    REFERENCES `oop`.`CERTIFICATE` (`cert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`PRODUCTS` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `item_description` VARCHAR(45) NOT NULL,
  `item_cost` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop`.`CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`CART` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `total_cost` INT NULL,
  INDEX `fk_CART_PRODUCTS1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_CART_USERS1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`item_id`, `user_id`),
  CONSTRAINT `fk_CART_PRODUCTS1`
    FOREIGN KEY (`item_id`)
    REFERENCES `oop`.`PRODUCTS` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CART_USERS1`
    FOREIGN KEY (`user_id`)
    REFERENCES `oop`.`USERS` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`ORDER` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `total_cost` INT NULL,
  `card_num` VARCHAR(45) NULL,
  `CVV` VARCHAR(45) NULL,
  `card_name` VARCHAR(45) NULL,
  `data` DATE NULL,
  INDEX `fk_ORDER_CART1_idx` (`item_id` ASC, `user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `item_id`),
  CONSTRAINT `fk_ORDER_CART1`
    FOREIGN KEY (`item_id` , `user_id`)
    REFERENCES `oop`.`CART` (`item_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop`.`ORDER_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop`.`ORDER_HISTORY` (
  `user_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `total_cost` INT NULL,
  `date` DATE NULL,
  INDEX `fk_ORDER_HISTORY_ORDER1_idx` (`user_id` ASC, `item_id` ASC) VISIBLE,
  CONSTRAINT `fk_ORDER_HISTORY_ORDER1`
    FOREIGN KEY (`user_id` , `item_id`)
    REFERENCES `oop`.`ORDER` (`user_id` , `item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
