USE [qwe]
GO

/****** Object:  Table [oop].[User]    Script Date: 06.06.2023 17:08:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[id] [int] NOT NULL,
	[cert_id] [int] NULL,
	[login] [nvarchar](45) NOT NULL,
	[password] [nvarchar](45) NOT NULL,
	[name] [nvarchar](45) NOT NULL,
	[email] [nvarchar](45) NULL,
	[number] [nvarchar](45) NOT NULL,
	[address] [nvarchar](45) NULL,
 CONSTRAINT [PK_users__id] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [users$_id_UNIQUE] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [users$CERTIFICATE_cert_id_UNIQUE] UNIQUE NONCLUSTERED 
(
	[cert_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [users$login_UNIQUE] UNIQUE NONCLUSTERED 
(
	[login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User] ADD  DEFAULT (NULL) FOR [email]
GO

ALTER TABLE [dbo].[User] ADD  DEFAULT (NULL) FOR [address]
GO

ALTER TABLE [dbo].[User]  WITH NOCHECK ADD  CONSTRAINT [users$fk_USERS_CERTIFICATE1] FOREIGN KEY([cert_id])
REFERENCES [dbo].[certificate] ([cert_id])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [users$fk_USERS_CERTIFICATE1]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_SSMA_SOURCE', @value=N'dbo.users' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'User'
GO


